apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
      app: restaurant-frontend
  template:
    metadata:
      labels:
        tier: frontend
        app: restaurant-frontend
    spec:
      containers:
      - name: frontend
        image: malikahsan13/restaurant-frontend-app:v0.0.1
        env:
        - name: BACKEND_URL
          value: backend:8000
        ports:
        - containerPort: 8000
          name: tcp

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    tier: frontend
    app: restaurant-frontend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31000